name: procenko
files_dir: "/home/altukhov/Data/speech_dl/Procenko/"
files_list:
    - "${..files_dir}/Patient001_test0042021.03.11_19.12.59.hdf5"
    - "${..files_dir}/Patient001_test0052021.03.11_19.26.24.hdf5"
    - "${..files_dir}/Patient001_test0062021.03.11_19.42.41.hdf5"
    - "${..files_dir}/Patient001_test0072021.03.11_20.40.02.hdf5"
    - "${..files_dir}/Patient001_test0082021.03.11_20.55.25.hdf5"
    - "${..files_dir}/Patient001_test0092021.03.11_21.10.53.hdf5"
sampling_rate: 19200
test_start_file_regression_index: 4
test_start_file_classification_index: 5
ecog_channels: ${python_range:"range(30)"}
notch_narrow_freqs: [70, 30, 60, 90, 100, 120, 150, 180, 210, 240, 270]
notch_wide_freqs: [50, 200, 250, 300]
sound_channel: 31
