name: meg_muscle
raw_path: "${oc.env:MEG_DATA}/02-apply_maxfilt/sub-01/sub-01_task-speech_proc-maxfiltannottwicecrop_meg.fif"
audio_path: "${oc.env:MEG_DATA}/07-align_speech/sub-01_proc-align_beh.wav"
annotations_path: "${oc.env:MEG_DATA}/06-annotate_muscles/sub-01/sub-01_task-speech_proc-badseg_annot.fif"
