defaults:
    - meg_subject_config
raw_path: "${oc.env:MEG_DATA}/091-resample/sub-02/sub-02_task-overtcovert_proc-resample_meg.fif"
audio_path: "${oc.env:MEG_DATA}/081-align_audio/sub-02/sub-02_task-overtcovert_proc-align_beh.wav"
annotations_path: "${oc.env:MEG_DATA}/071-annotate_muscles/sub-02/sub-02_task-overtcovert_proc-ica_annot.fif"

