defaults:
  - simple_net_base
  - _self_
use_lstm: False
feature_extractor:
  downsampling: 10             # downsampling coefficient for envelopes
  hidden_channels: 4           # must be even
  filtering_size: 25          # in samples
  envelope_size: 15           # in samples
