defaults:
    - patient: procenko
    - _self_

_target_: library.datasets.EcogDataset.from_config
transform:
    _target_: library.common_preprocessing.ClassicEcogPipeline
    dsamp_coef: 19
    lowpass: 200
    highpass: 10
    sampling_rate: ${..patient.sampling_rate}
    selected_channels: ${selected_channels}
target_transformer:
    _target_: library.common_preprocessing.ClassicMelspectrogramPipeline
    dsamp_coef: ${..transform.dsamp_coef}
    n_mels: ${target_features_cnt}
    f_max: 2000
lag_backward: ${lag_backward}
lag_forward: ${lag_forward}
