defaults:
    - patient: ecog_procenko
    - _self_

_target_: library.datasets.EcogDataset.from_config
transform:
    _target_: library.common_preprocessing.ClassicEcogPipeline
    dsamp_coef: 19
    lowpass: 200  # remove target leakage
    highpass: 10  # remove EoG artifacts
    notch_narrow_freqs: ${..patient.notch_narrow_freqs}
    notch_wide_freqs: ${..patient.notch_wide_freqs}
    selected_channels: ${selected_channels}
target_transform:
    _target_: library.common_preprocessing.ClassicMelspectrogramPipeline
    dsamp_coef: ${..transform.dsamp_coef}
    n_mels: ${target_features_cnt}
    f_max: 2000
lag_backward: ${lag_backward}
lag_forward: ${lag_forward}
