defaults:
  - dataset_schema
  - subject: meg_clean
  - _self_

type: MEG

read:
  _target_: ndp.datasets.speech_meg.read
  subject: ${..subject}

transform_x:
  _target_: library.transformers.MegPipeline
  l_freq: 10
  h_freq: 120
  notch_freqs: [50, 100]
  selected_channels: ${selected_channels}
transform_y:
  _target_: library.transformers.MelspectrogramPipeline
  dsamp_coef: 22
  n_mels: ${target_features_cnt}
  f_max: 2000
