defaults:
  - dataset_schema
  - _self_

type: MEG

read:
  _target_: ndp.datasets.speech_meg.read
  subject: ${..subject}

transform_x:
  _target_: library.transformers.MegPipeline
  l_freq: 1
  h_freq: 120
  notch_freqs: []
  selected_channels: ${selected_channels}
