defaults:
    - patient: simulated
    - _self_

_target_: library.datasets.SimulatedDataset.from_config
transform:
    _target_: library.transformers.Scaler
target_transform:
    _target_: library.transformers.Scaler
lag_backward: ${lag_backward}
lag_forward: ${lag_forward}
