name: meg_muscle
files_dir: "/home/altukhov/Data/speech/rawdata/derivatives/"
raw_path: "${.files_dir}/02-apply_maxfilt/sub-01/sub-01_task-speech_proc-maxfiltannottwicecrop_meg.fif"
audio_align_path: "${.files_dir}/06-align_speech/sub-01_proc-align_beh.wav"
